# **NUMPY ASSIGNMENT**

**Name: GANESH D**

**Reg.No: 212223240035**

**Question 1:  Student Marks Array**


In [ ]:
import numpy as np

marks = np.array([78, 65, 89, 56, 92])

print("Marks:", marks)
print("Number of dimensions:", marks.ndim)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data type:", marks.dtype)

Marks: [78 65 89 56 92]
Number of dimensions: 1
Shape: (5,)
Size: 5
Data type: int64


**Question 2 – Student Marks Access**

In [ ]:
import numpy as np

marks = np.array([72, 85, 64, 90, 76])

print("Marks:", marks)

print("First student:", marks[0])
print("Third student:", marks[2])
print("Last student:", marks[-1])

print("First three students:", marks[0:3])
print("Second to fourth students:", marks[1:4])

Marks: [72 85 64 90 76]
First student: 72
Third student: 64
Last student: 76
First three students: [72 85 64]
Second to fourth students: [85 64 90]


**Question 3 – Subject-wise Marks**

In [ ]:
import numpy as np

marks = np.array([
    78, 85, 90,
    65, 72, 80,
    88, 91, 84,
    56, 62, 70,
    95, 89, 92
])

matrix = marks.reshape(5, 3)

print("Original Array:")
print(marks)

print("\n5 x 3 Matrix:")
print(matrix)

Original Array:
[78 85 90 65 72 80 88 91 84 56 62 70 95 89 92]

5 x 3 Matrix:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


**Question 4 – Internal and External Marks**

In [ ]:
import numpy as np

internal = np.array([20, 18, 19, 17, 16])
external = np.array([65, 70, 68, 72, 75])

final_marks = internal + external

print("Internal Marks:", internal)
print("External Marks:", external)
print("Final Marks:", final_marks)

Internal Marks: [20 18 19 17 16]
External Marks: [65 70 68 72 75]
Final Marks: [85 88 87 89 91]


**Question 5 – Pass Percentage Analysis**

In [ ]:
import numpy as np

marks = np.array([45, 78, 56, 32, 91])

passed = marks >= 50

print("Marks:", marks)
print("Pass/Fail:", passed)
print("Students who scored 50 or above:", marks[passed])

Marks: [45 78 56 32 91]
Pass/Fail: [False  True  True False  True]
Students who scored 50 or above: [78 56 91]


**Question 6 – Average Marks**

In [ ]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

average = np.mean(marks, axis=1)

print("Marks:")
print(marks)

print("\nAverage marks of each student:")
print(average)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Average marks of each student:
[84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


**Question 7 – Class Performance Statistics**

In [ ]:
import numpy as np

marks = np.array([67, 82, 91, 74, 58])

print("Marks:", marks)

print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard Deviation:", np.std(marks))

Marks: [67 82 91 74 58]
Total: 372
Average: 74.4
Highest: 91
Lowest: 58
Standard Deviation: 11.46472851837321


**Question 8 – Subject-wise Performance**

In [ ]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

subject_total = np.sum(marks, axis=0)

print("Marks:")
print(marks)

print("\nTotal marks in each subject:")
print(subject_total)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Total marks in each subject:
[382 399 416]


**Question 9 – Student-wise Performance**

In [ ]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

student_total = np.sum(marks, axis=1)

print("Marks:")
print(marks)

print("\nTotal marks of each student:")
print(student_total)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Total marks of each student:
[253 217 263 188 276]


**Question 10 – Student Ranking**

In [ ]:
import numpy as np

marks = np.array([245, 278, 219, 290, 256])

sorted_marks = np.sort(marks)[::-1]

ranking = np.argsort(marks)[::-1]

print("Original Marks:", marks)

print("\nMarks in descending order:")
print(sorted_marks)

print("\nStudent ranking:")
for rank, index in enumerate(ranking, start=1):
    print("Rank", rank, "- Student", index + 1,
          "- Marks:", marks[index])

Original Marks: [245 278 219 290 256]

Marks in descending order:
[290 278 256 245 219]

Student ranking:
Rank 1 - Student 4 - Marks: 290
Rank 2 - Student 2 - Marks: 278
Rank 3 - Student 5 - Marks: 256
Rank 4 - Student 1 - Marks: 245
Rank 5 - Student 3 - Marks: 219


**Question 11 – Duplicate Marks Analysis**

In [ ]:
import numpy as np

marks = np.array([85, 92, 85, 76, 92])

unique_marks = np.unique(marks)

print("Marks:", marks)
print("Unique marks:", unique_marks)

Marks: [85 92 85 76 92]
Unique marks: [76 85 92]


**Question 12 – Missing Marks**

In [ ]:
import numpy as np

marks = np.array([78, 85, np.nan, 92, 67])

average = np.nanmean(marks)

print("Marks:", marks)
print("Average without missing value:", average)

Marks: [78. 85. nan 92. 67.]
Average without missing value: 80.5


**Question 13 – Grade Classification**

In [ ]:
import numpy as np

marks = np.array([95, 82, 74, 61, 45])

grades = np.select(
    [
        marks >= 90,
        marks >= 80,
        marks >= 70,
        marks >= 60
    ],
    [
        "A",
        "B",
        "C",
        "D"
    ],
    default="F"
)

print("Marks:", marks)
print("Grades:", grades)

Marks: [95 82 74 61 45]
Grades: ['A' 'B' 'C' 'D' 'F']


**Question 14 – Random Marks Generation**

In [ ]:
import numpy as np

np.random.seed(10)

marks = np.random.randint(0, 101, 5)

print("Generated Marks:", marks)

print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard Deviation:", np.std(marks))

Generated Marks: [  9 100  15  64  28]
Total: 216
Average: 43.2
Highest: 100
Lowest: 9
Standard Deviation: 34.219292803913994


**Question 15 – Student Performance Analysis**

In [ ]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

print("Student Marks:")
print(marks)

total = np.sum(marks, axis=1)

average = np.mean(marks, axis=1)

highest = np.max(marks, axis=1)

lowest = np.min(marks, axis=1)

class_average = np.mean(marks)

above_average = total / 3 > class_average

print("\nTotal Marks:")
print(total)

print("\nAverage Marks:")
print(average)

print("\nHighest Marks:")
print(highest)

print("\nLowest Marks:")
print(lowest)

print("\nClass Average:", class_average)

print("\nStudents above class average:")

for i in range(5):
    if above_average[i]:
        print("Student", i + 1)

Student Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Total Marks:
[253 217 263 188 276]

Average Marks:
[84.33333333 72.33333333 87.66666667 62.66666667 92.        ]

Highest Marks:
[90 80 91 70 95]

Lowest Marks:
[78 65 84 56 89]

Class Average: 79.8

Students above class average:
Student 1
Student 3
Student 5


# **Python Assignments:**


In [ ]:
start = int(input("Enter starting number: "))
end = int(input("Enter ending number: "))

print("Prime numbers:")

for num in range(start, end + 1):

    if num < 2:
        continue

    prime = True

    for i in range(2, num):
        if num % i == 0:
            prime = False
            break

    if prime:
        print(num, end=" ")

Enter starting number: 20
Enter ending number: 50
Prime numbers:
23 29 31 37 41 43 47 

In [ ]:
def factorial(n):

    if n == 0 or n == 1:
        return 1

    return n * factorial(n - 1)


n = int(input("Enter a number: "))

result = factorial(n)

print("Factorial:", result)

Enter a number: 5
Factorial: 120


In [ ]:
square = lambda x: x * x

n = int(input("Enter a number: "))

print("Square:", square(n))

Enter a number: 8
Square: 64


In [ ]:
numbers = list(map(int,input().split()))

numbers = list(set(numbers))

numbers.sort()

print("List:", numbers)

print("Second largest:", numbers[-2])

8 10 25 30 45
List: [8, 10, 25, 30, 45]
Second largest: 30


In [ ]:
text = input("Enter the string: ")

d = {}

for ch in text:
    if ch in d:
        d[ch] += 1
    else:
        d[ch] = 1

for char, count in d.items():
    print(char, ":", count)

Enter the string: hello
h : 1
e : 1
l : 2
o : 1


In [ ]:
import math

r = float(input("Enter the radius: "))

area = math.pi * r * r

print("Area of circle: ",area)

Enter the radius: 5
Area of circle:  78.53981633974483


In [ ]:
text = input("Enter the string: ")

rev = ""

for ch in text:
    rev = ch + rev

print(rev)

Enter the string: Ganesh
hsenaG


In [ ]:
numbers = list(map(int,input().split()))

result = []

for n in numbers:
    if n not in result:
        result.append(n)

print("Remove duplicates from a list:",result)

10 20 10 30 20 40
Remove duplicates from a list: [10, 20, 30, 40]


In [ ]:
d1 = {"a": 10, "b": 20}
d2 = {"c": 30, "d": 40}

d1.update(d2)

print("Merge two dictionaries: ",d1)

Merge two dictionaries:  {'a': 10, 'b': 20, 'c': 30, 'd': 40}


In [ ]:
def fib(n):
    if n <= 1:
        return n
    return fib(n - 1) + fib(n - 2)

n = int(input("Enter the number: "))

print("Fibonacci series: ")
for i in range(n):
    print(fib(i), end=" ")

Enter the number: 5
Fibonacci series: 
0 1 1 2 3 

# **Python Function Assignments**

In [ ]:
def calculate(a, b, operation):

    if operation == "+":
        return a + b

    elif operation == "-":
        return a - b

    elif operation == "*":
        return a * b

    elif operation == "/":
        return a / b

    else:
        return "Invalid operation"


a = int(input())
b = int(input())
operation = input()

print(calculate(a, b, operation))

18
3
/
6.0


In [ ]:
def sum_numbers(*args):

    total = 0

    for n in args:
        total = total + n

    return total

nums=list(map(int,input().split()))
print(sum_numbers(*nums))

10 20 30
60


In [ ]:
def employee(**args):

    for key, value in args.items():
        print(key, ":", value)


employee(
    name="Ganesh",
    ID=101,
    department="Testing",
    salary=30000
)

name : Ganesh
ID : 101
department : Testing
salary : 30000


In [ ]:
def remove_duplicates(lst):

    result = []

    for n in lst:
        if n not in result:
            result.append(n)

    return result


numbers = list(map(int,input().split()))

print(remove_duplicates(numbers))

10 15 20 15 25 20
[10, 15, 20, 25]


In [ ]:
numbers = []

n = int(input("Enter number of tuples: "))

for i in range(n):
    a, b = map(int, input().split())
    numbers.append((a, b))

numbers.sort(key=lambda x: x[1])

print(numbers)

Enter number of tuples: 3
1 5
2 3
4 1
[(4, 1), (2, 3), (1, 5)]
